### ISSUE TITLE
broken due to libjpeg.so.9 dependency missing?

### ISSUE THREAD

**Issue by lexual** [conda-forge/python-eccodes-feedstock#6]
this appears broken!

See below.

	$ python -c 'import eccodes'
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/home/lexbom/miniconda3/envs/jiptc_localdev/lib/python2.7/site-packages/eccodes/__init__.py", line 1, in <module>
	    from .eccodes import *
	  File "/home/lexbom/miniconda3/envs/jiptc_localdev/lib/python2.7/site-packages/eccodes/eccodes.py", line 1, in <module>
	    from gribapi import __version__
	  File "/home/lexbom/miniconda3/envs/jiptc_localdev/lib/python2.7/site-packages/gribapi/__init__.py", line 1, in <module>
	    from .gribapi import *                # noqa
	  File "/home/lexbom/miniconda3/envs/jiptc_localdev/lib/python2.7/site-packages/gribapi/gribapi.py", line 27, in <module>
	    import gribapi_swig as _internal
	  File "/home/lexbom/miniconda3/envs/jiptc_localdev/lib/python2.7/site-packages/gribapi/gribapi_swig.py", line 25, in <module>
	    _gribapi_swig = swig_import_helper()
	  File "/home/lexbom/miniconda3/envs/jiptc_localdev/lib/python2.7/site-packages/gribapi/gribapi_swig.py", line 21, in swig_import_helper
	    _mod = imp.load_module('_gribapi_swig', fp, pathname, description)
	ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory

conda env export

    name: my_env
    channels: !!python/tuple
    - defaults
    - conda-forge
    dependencies:
    - conda-forge::boost=1.61.0=py27_1
    - conda-forge::eccodes=0.13.0=2
    - conda-forge::icu=56.1=4
    - conda-forge::jasper=1.900.1=1
    - conda-forge::perl=5.20.3.1=1
    - conda-forge::python-eccodes=0.13.0=np111py27_1
    - curl=7.49.0=1
    - hdf4=4.2.12=0
    - hdf5=1.8.17=1
    - jpeg=8d=2
    - libnetcdf=4.4.1=0
    - libpng=1.6.22=0
    - mkl=11.3.3=0
    - numpy=1.11.2=py27_0
    - openssl=1.0.2j=0
    - pandas=0.19.0=np111py27_0
    - pip=8.1.2=py27_0
    - py=1.4.31=py27_0
    - pytest=3.0.3=py27_0
    - python=2.7.12=1
    - python-dateutil=2.5.3=py27_0
    - pytz=2016.7=py27_0
    - readline=6.2=2
    - setuptools=27.2.0=py27_0
    - six=1.10.0=py27_0
    - sqlite=3.13.0=0
    - tk=8.5.18=0
    - wheel=0.29.0=py27_0
    - zlib=1.2.8=3
    prefix: /home/blah/miniconda3/envs/foo

**Comment by lexual** [comment]
hmm, looks to be due to interaction of 'default' channel packages and conda packages.

**Comment by ocefpaf** [comment]
if you are going to use conda-forge you need to reverse the channel order 

```yaml
channels: !!python/tuple
- conda-forge
- defaults
```

to get a consistent set of dependencies.
